apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springdemo
  name: springdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springdemo
    spec:
      containers:
      - image: phanee47/springtest:6
        name: springdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: springdemo